version: '3.7'
services:
  db:
    image: wqp_db
    build:
      context: .
    networks:
      wqp:
        ipv4_address: ${DB_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5434:5432
    container_name: ${DATABASE_ADDRESS}

  liquibase:
    image: wqp_liquibase
    build:
      context: ./liquibase
      args:
        - LIQUIBASE_VERSION=${LIQUIBASE_VERSION}
        - A_JDBC_JAR=${JDBC_JAR}
    networks:
      wqp:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATA_OWNER=${DATA_OWNER}
      - DATA_OWNER_PASSWORD=${DATA_OWNER_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - SCHEMA_NAME=${SCHEMA_NAME}
      - READ_ONLY_USER=${READ_ONLY_USER}
      - READ_ONLY_USER_PASSWORD=${READ_ONLY_USER_PASSWORD}
      - CONTEXTS=${CONTEXTS}
      - DATABASE_ADDRESS=${DATABASE_ADDRESS}

  liquibase_demo:
    image: wqp_liquibase_demo
    build:
      context: ./liquibase
      dockerfile: Dockerfile.demo
    networks:
      wqp:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATA_OWNER=${DATA_OWNER}
      - DATA_OWNER_PASSWORD=${DATA_OWNER_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - SCHEMA_NAME=${SCHEMA_NAME}
      - READ_ONLY_USER=${READ_ONLY_USER}
      - READ_ONLY_USER_PASSWORD=${READ_ONLY_USER_PASSWORD}
      - CONTEXTS=external,dev
      - DATABASE_ADDRESS=${DATABASE_ADDRESS}
    volumes:
      - ./liquibase/changeLogs:/opt/liquibase/workspace
      - ./liquibase/logs:/opt/liquibase/logs
      - ./liquibase/dbDemo:/docker-entrypoint-initdb.d

networks:
  wqp:
    external:
      name: wqp
