version: '3.7'
services:

  ciDB:
    image: wqp_db_ci
    build:
      context: .
      dockerfile: ./database/ci/Dockerfile
    networks:
      wqp:
        ipv4_address: ${DB_CI_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${WQP_DATABASE_NAME}
      - WQP_DATABASE_NAME=${WQP_DATABASE_NAME}
      - WQP_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - WQP_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - WQP_SCHEMA_NAME=${WQP_SCHEMA_NAME}
      - WQP_SCHEMA_OWNER_USERNAME=${WQP_SCHEMA_OWNER_USERNAME}
      - WQP_SCHEMA_OWNER_PASSWORD=${WQP_SCHEMA_OWNER_PASSWORD}
      - WQP_READ_ONLY_USERNAME=${WQP_READ_ONLY_USERNAME}
      - WQP_READ_ONLY_PASSWORD=${WQP_READ_ONLY_PASSWORD}
      - CONTEXTS=external,ci,schemaLoad
      - WQP_DATABASE_ADDRESS=127.0.0.1
    ports:
      - ${DB_CI_PORT}:5432
    container_name: ${WQP_DATABASE_ADDRESS}_ci

  demoDB:
    image: wqp_db_demo
    build:
      context: .
      dockerfile: ./database/demo/Dockerfile
    networks:
      wqp:
        ipv4_address: ${DB_DEMO_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${WQP_DATABASE_NAME}
      - WQP_DATABASE_NAME=${WQP_DATABASE_NAME}
      - WQP_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - WQP_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - WQP_SCHEMA_NAME=${WQP_SCHEMA_NAME}
      - WQP_SCHEMA_OWNER_USERNAME=${WQP_SCHEMA_OWNER_USERNAME}
      - WQP_SCHEMA_OWNER_PASSWORD=${WQP_SCHEMA_OWNER_PASSWORD}
      - WQP_READ_ONLY_USERNAME=${WQP_READ_ONLY_USERNAME}
      - WQP_READ_ONLY_PASSWORD=${WQP_READ_ONLY_PASSWORD}
      - CONTEXTS=external,dev
      - WQP_DATABASE_ADDRESS=127.0.0.1
    ports:
      - ${DB_DEMO_PORT}:5432
    container_name: ${WQP_DATABASE_ADDRESS}_dev

  db:
    image: wqp_db
    build:
      context: .
    networks:
      wqp:
        ipv4_address: ${DB_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${WQP_DATABASE_NAME}
    ports:
      - ${DB_PORT}:5432
    container_name: ${WQP_DATABASE_ADDRESS}

  liquibase:
    image: wqp_liquibase
    build:
      context: ./liquibase
      args:
        - LIQUIBASE_VERSION=${LIQUIBASE_VERSION}
        - A_JDBC_JAR=${JDBC_JAR}
    networks:
      wqp:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WQP_DATABASE_NAME=${WQP_DATABASE_NAME}
      - WQP_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - WQP_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - WQP_SCHEMA_NAME=${WQP_SCHEMA_NAME}
      - WQP_SCHEMA_OWNER_USERNAME=${WQP_SCHEMA_OWNER_USERNAME}
      - WQP_SCHEMA_OWNER_PASSWORD=${WQP_SCHEMA_OWNER_PASSWORD}
      - WQP_READ_ONLY_USERNAME=${WQP_READ_ONLY_USERNAME}
      - WQP_READ_ONLY_PASSWORD=${WQP_READ_ONLY_PASSWORD}
      - CONTEXTS=${CONTEXTS}
      - WQP_DATABASE_ADDRESS=${WQP_DATABASE_ADDRESS}
    volumes:
      - ./liquibase/changeLogs:/home/java/workspace/wqp
      - ./liquibase/scripts/dbInit:/docker-entrypoint-initdb.d
    container_name: wqp_liquibase

  etlDB:
    image: wqp_db_etl
    build:
      context: .
      dockerfile: ./database/etl/Dockerfile
      args:
        - ARS_REPO_ZIP_URL=${ARS_REPO_ZIP_URL}
        - BIODATA_REPO_ZIP_URL=${BIODATA_REPO_ZIP_URL}
        - NWIS_REPO_ZIP_URL=${NWIS_REPO_ZIP_URL}
    networks:
      wqp:
        ipv4_address: ${DB_ETL_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${WQP_DATABASE_NAME}
      - WQP_DATABASE_ADDRESS=127.0.0.1
      - WQP_DATABASE_NAME=${WQP_DATABASE_NAME}
      - WQP_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - WQP_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - WQP_SCHEMA_NAME=${WQP_SCHEMA_NAME}
      - WQP_SCHEMA_OWNER_USERNAME=${WQP_SCHEMA_OWNER_USERNAME}
      - WQP_SCHEMA_OWNER_PASSWORD=${WQP_SCHEMA_OWNER_PASSWORD}
      - WQP_READ_ONLY_USERNAME=${WQP_READ_ONLY_USERNAME}
      - WQP_READ_ONLY_PASSWORD=${WQP_READ_ONLY_PASSWORD}
      - CONTEXTS=${CONTEXTS}
      - ARS_DATABASE_ADDRESS=127.0.0.1
      - ARS_DATABASE_NAME=${WQP_DATABASE_NAME}
      - ARS_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - ARS_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - ARS_SCHEMA_NAME=${ARS_SCHEMA_NAME}
      - ARS_SCHEMA_OWNER_USERNAME=${ARS_SCHEMA_OWNER_USERNAME}
      - ARS_SCHEMA_OWNER_PASSWORD=${ARS_SCHEMA_OWNER_PASSWORD}
      - BIODATA_DATABASE_ADDRESS=127.0.0.1
      - BIODATA_DATABASE_NAME=${WQP_DATABASE_NAME}
      - BIODATA_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - BIODATA_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - BIODATA_SCHEMA_NAME=${BIODATA_SCHEMA_NAME}
      - BIODATA_SCHEMA_OWNER_USERNAME=${BIODATA_SCHEMA_OWNER_USERNAME}
      - BIODATA_SCHEMA_OWNER_PASSWORD=${BIODATA_SCHEMA_OWNER_PASSWORD}
      - NWIS_DATABASE_ADDRESS=127.0.0.1
      - NWIS_DATABASE_NAME=${WQP_DATABASE_NAME}
      - NWIS_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - NWIS_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - NWIS_SCHEMA_NAME=${NWIS_SCHEMA_NAME}
      - NWIS_SCHEMA_OWNER_USERNAME=${NWIS_SCHEMA_OWNER_USERNAME}
      - NWIS_SCHEMA_OWNER_PASSWORD=${NWIS_SCHEMA_OWNER_PASSWORD}
      - EPA_DATABASE_ADDRESS=127.0.0.1
      - EPA_DATABASE_NAME=${WQP_DATABASE_NAME}
      - EPA_DB_OWNER_USERNAME=${WQP_DB_OWNER_USERNAME}
      - EPA_DB_OWNER_PASSWORD=${WQP_DB_OWNER_PASSWORD}
      - EPA_SCHEMA_OWNER_USERNAME=${EPA_SCHEMA_OWNER_USERNAME}
      - EPA_SCHEMA_OWNER_PASSWORD=${EPA_SCHEMA_OWNER_PASSWORD}
      - WQX_SCHEMA_NAME=${WQX_SCHEMA_NAME}
      - STORETW_SCHEMA_NAME=${STORETW_SCHEMA_NAME}
    ports:
      - ${DB_ETL_PORT}:5432
    container_name: ${WQP_DATABASE_ADDRESS}_etl

networks:
  wqp:
    external:
      name: ${LOCAL_NETWORK_NAME}
